# Generated by Django 3.2.5 on 2021-07-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20210714_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
