# Generated by Django 3.2.5 on 2021-07-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
