# Generated by Django 3.2.5 on 2021-07-15 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_certificate_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='quali',
            field=models.CharField(max_length=89, null=True),
        ),
    ]
